theory Top1
  imports Complex_Main
begin

(*
  Formalization stubs (statements only, no proofs) for /mnt/data/top1.tex

  Notes:
  - This file is intended to mirror the mathematical content of top1.tex
    (Munkres, Chapter 2, §§12–17) at the level of definitions and stated results.
  - Proofs are omitted using 'sorry' (no axioms).
*)

section \<open>\<S>12 Topological Spaces\<close>

(** from \S12 Definition (Topology on a set) [top1.tex:49] **)
(** LATEX VERSION: "A topology on a set X is a collection T of subsets of X ..." **)
definition is_topology_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_topology_on X T \<longleftrightarrow>
     {} \<in> T \<and> X \<in> T \<and>
     (\<forall>U. U \<subseteq> T \<longrightarrow> (\<Union>U) \<in> T) \<and>
     (\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> (\<Inter>F) \<in> T)"

(** from \S12 (Open set terminology) [top1.tex:~55] **)
(** LATEX VERSION: "U is open in X iff U \<in> T." **)
definition openin_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "openin_on X T U \<longleftrightarrow> U \<in> T"

(** from \S12 Definition (Finer/coarser/comparable) [top1.tex:96] **)
(** LATEX VERSION: "T' is finer than T iff T \<subseteq> T' ..." **)
definition finer_than :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "finer_than T T' \<longleftrightarrow> T \<subseteq> T'"

definition strictly_finer_than :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "strictly_finer_than T T' \<longleftrightarrow> T \<subseteq> T' \<and> T \<noteq> T'"

definition comparable_topologies :: "'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "comparable_topologies T T' \<longleftrightarrow> (T \<subseteq> T' \<or> T' \<subseteq> T)"


section \<open>\<S>13 Basis for a Topology\<close>

(** from \S13 Definition (Basis for a topology) [top1.tex:109] **)
(** LATEX VERSION: "B is a basis on X if (1) covers X and (2) intersection condition..." **)
definition is_basis_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_basis_on X B \<longleftrightarrow>
     (\<forall>x\<in>X. \<exists>b\<in>B. x \<in> b) \<and>
     (\<forall>b1\<in>B. \<forall>b2\<in>B. \<forall>x\<in>(b1 \<inter> b2).
         \<exists>b3\<in>B. x \<in> b3 \<and> b3 \<subseteq> (b1 \<inter> b2))"

(** from \S13 Definition (Topology generated by a basis) [top1.tex:109] **)
(** LATEX VERSION: "U is open iff for each x\<in>U there is basis element B with x\<in>B\<subseteq>U." **)
definition topology_generated_by_basis :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set" where
  "topology_generated_by_basis X B =
     {U. U \<subseteq> X \<and> (\<forall>x\<in>U. \<exists>b\<in>B. x \<in> b \<and> b \<subseteq> U)}"

(** Convenience: "B is a basis for T on X" [implicit throughout \S13] **)
definition basis_for :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "basis_for X B T \<longleftrightarrow> is_basis_on X B \<and> T = topology_generated_by_basis X B"

(** from \S13 Lemma 13.1 [top1.tex:168] **)
(** LATEX VERSION: "T equals the collection of all unions of elements of B." **)
theorem Lemma_13_1:
  assumes "basis_for X B T"
  shows "T = { \<Union>U | U. U \<subseteq> B }"
  sorry

(** from \S13 Lemma 13.2 [top1.tex:176] **)
(** LATEX VERSION: "If C is a collection of open sets with local refinement property, then C is a basis." **)
theorem Lemma_13_2:
  assumes "is_topology_on X T"
  assumes "\<And>U x. U \<in> T \<Longrightarrow> x \<in> U \<Longrightarrow> \<exists>C\<in>Cc. C \<in> T \<and> x \<in> C \<and> C \<subseteq> U"
  shows "basis_for X Cc T"
  sorry

(** from \S13 Lemma 13.3 [top1.tex:184] **)
(** LATEX VERSION: "Criterion for T' finer than T in terms of bases." **)
theorem Lemma_13_3:
  assumes "basis_for X B T"
  assumes "basis_for X B' T'"
  shows "finer_than T T' \<longleftrightarrow>
    (\<forall>x\<in>X. \<forall>b\<in>B. x \<in> b \<longrightarrow> (\<exists>b'\<in>B'. x \<in> b' \<and> b' \<subseteq> b))"
  sorry


subsection \<open>Standard, lower limit, and K-topologies on \<real>\<close>

(** from \S13 Definition (standard, lower limit, K-topology) [top1.tex:205] **)
(** LATEX VERSION: "standard basis (a,b); lower limit basis [a,b); K basis (a,b) and (a,b)-K." **)

definition interval_open :: "real \<Rightarrow> real \<Rightarrow> real set" where
  "interval_open a b = {x. a < x \<and> x < b}"

definition interval_half_open_left_closed :: "real \<Rightarrow> real \<Rightarrow> real set" where
  "interval_half_open_left_closed a b = {x. a \<le> x \<and> x < b}"

definition K_set :: "real set" where
  "K_set = {x. \<exists>n::nat. n > 0 \<and> x = 1 / real n}"

definition basis_standard_R :: "real set set" where
  "basis_standard_R = { interval_open a b | a b. a < b }"

definition basis_lower_limit_R :: "real set set" where
  "basis_lower_limit_R = { interval_half_open_left_closed a b | a b. a < b }"

definition basis_K_topology_R :: "real set set" where
  "basis_K_topology_R =
     ({ interval_open a b | a b. a < b } \<union>
      { interval_open a b - K_set | a b. a < b })"

definition topology_standard_R :: "real set set" where
  "topology_standard_R = topology_generated_by_basis UNIV basis_standard_R"

definition topology_lower_limit_R :: "real set set" where
  "topology_lower_limit_R = topology_generated_by_basis UNIV basis_lower_limit_R"

definition topology_K_R :: "real set set" where
  "topology_K_R = topology_generated_by_basis UNIV basis_K_topology_R"

(** from \S13 Lemma 13.4 [top1.tex:221] **)
(** LATEX VERSION: "R_l and R_K are strictly finer than standard, but not comparable." **)
theorem Lemma_13_4:
  shows "strictly_finer_than topology_standard_R topology_lower_limit_R
       \<and> strictly_finer_than topology_standard_R topology_K_R
       \<and> \<not> comparable_topologies topology_lower_limit_R topology_K_R"
  sorry


subsection \<open>Subbasis\<close>

(** from \S13 Definition (Subbasis and generated topology) [top1.tex:231] **)
(** LATEX VERSION: "S subbasis: \<Union>S = X; topology is unions of finite intersections of S." **)
definition is_subbasis_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_subbasis_on X S \<longleftrightarrow> (\<Union>S = X)"

definition finite_intersections :: "'a set set \<Rightarrow> 'a set set" where
  "finite_intersections S =
     { \<Inter>F | F. finite F \<and> F \<subseteq> S }"

definition topology_generated_by_subbasis :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set set" where
  "topology_generated_by_subbasis X S =
     { \<Union>U | U. U \<subseteq> finite_intersections S }"


section \<open>\<S>14 The Order Topology\<close>

(** from \S14 Definition (Order topology on a simply ordered set) [top1.tex:314] **)
(** LATEX VERSION: "Order topology generated by open intervals and rays." **)

definition open_ray_gt :: "'a::linorder \<Rightarrow> 'a set" where
  "open_ray_gt a = {x. a < x}"

definition open_ray_lt :: "'a::linorder \<Rightarrow> 'a set" where
  "open_ray_lt a = {x. x < a}"

definition open_interval :: "'a::linorder \<Rightarrow> 'a \<Rightarrow> 'a set" where
  "open_interval a b = {x. a < x \<and> x < b}"

definition basis_order_topology :: "'a::linorder set set" where
  "basis_order_topology =
     ({ open_interval a b | a b. a < b } \<union>
      { open_ray_gt a | a. True } \<union>
      { open_ray_lt a | a. True })"

definition order_topology_on_UNIV :: "'a::linorder set set" where
  "order_topology_on_UNIV = topology_generated_by_basis UNIV basis_order_topology"

(** from \S14 Definition (Four interval types determined by a and b) [top1.tex:345] **)
(** LATEX VERSION: "If X ordered and a element, there are four intervals ..." **)
definition interval_types_four :: "'a::linorder \<Rightarrow> 'a \<Rightarrow> 'a set list" where
  "interval_types_four a b =
     [ {x. a < x \<and> x < b},
       {x. a \<le> x \<and> x < b},
       {x. a < x \<and> x \<le> b},
       {x. a \<le> x \<and> x \<le> b} ]"


section \<open>\<S>15 The Product Topology on X \<times> Y\<close>

(** from \S15 Definition (Product topology) [top1.tex:365] **)
(** LATEX VERSION: "Product topology generated by basis {U\<times>V | U open in X, V open in Y}." **)

definition product_basis :: "'a set set \<Rightarrow> 'b set set \<Rightarrow> ('a \<times> 'b) set set" where
  "product_basis TX TY =
     { U \<times> V | U V. U \<in> TX \<and> V \<in> TY }"

definition product_topology_on :: "'a set set \<Rightarrow> 'b set set \<Rightarrow> ('a \<times> 'b) set set" where
  "product_topology_on TX TY =
     topology_generated_by_basis UNIV (product_basis TX TY)"

(** from \S15 Definition (Projections) [top1.tex:401] **)
(** LATEX VERSION: "\<pi>1(x,y)=x, \<pi>2(x,y)=y." **)
definition pi1 :: "'a \<times> 'b \<Rightarrow> 'a" where "pi1 p = fst p"
definition pi2 :: "'a \<times> 'b \<Rightarrow> 'b" where "pi2 p = snd p"

definition preimage :: "('a \<Rightarrow> 'b) \<Rightarrow> 'b set \<Rightarrow> 'a set" where
  "preimage f U = {x. f x \<in> U}"

(** from \S15 Theorem 15.1 [top1.tex:379] **)
(** LATEX VERSION: "If B,C bases for X,Y then {B\<times>C} is a basis for X\<times>Y." **)
theorem Theorem_15_1:
  assumes "basis_for UNIV BX TX"
  assumes "basis_for UNIV BY TY"
  defines "D \<equiv> {B \<times> C | B C. B \<in> BX \<and> C \<in> BY}"
  shows "basis_for UNIV D (product_topology_on TX TY)"
  sorry

(** from \S15 Theorem 15.2 [top1.tex:425] **)
(** LATEX VERSION: "Subbasis for product topology: preimages of opens under projections." **)
theorem Theorem_15_2:
  assumes "is_topology_on UNIV TX"
  assumes "is_topology_on UNIV TY"
  defines "S \<equiv> { preimage pi1 U | U. U \<in> TX } \<union> { preimage pi2 V | V. V \<in> TY }"
  shows "product_topology_on TX TY = topology_generated_by_subbasis UNIV S"
  sorry


section \<open>\<S>16 The Subspace Topology\<close>

(** from \S16 Definition (Subspace topology) [top1.tex:450] **)
(** LATEX VERSION: "T_Y = {Y \<inter> U | U \<in> T}." **)
definition subspace_topology :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set set" where
  "subspace_topology X T Y = {Y \<inter> U | U. U \<in> T}"

(** from \S16 Lemma 16.1 [top1.tex:473] **)
(** LATEX VERSION: "If B is a basis for X, then {B\<inter>Y} is a basis for subspace topology on Y." **)
theorem Lemma_16_1:
  fixes Y :: "'a set"
  assumes "basis_for X B T"
  defines "BY \<equiv> {b \<inter> Y | b. b \<in> B}"
  shows "basis_for Y BY (subspace_topology X T Y)"
  sorry

(** from \S16 Lemma 16.2 [top1.tex:486] **)
(** LATEX VERSION: "If U open in Y and Y open in X, then U open in X." **)
theorem Lemma_16_2:
  assumes "is_topology_on X T"
  assumes "Y \<in> T"  (* Y open in X *)
  assumes "U \<in> subspace_topology X T Y"
  shows "U \<in> T"
proof -
  from assms(3) obtain V where hV: "V \<in> T" and hU: "U = Y \<inter> V"
    unfolding subspace_topology_def by blast
  from assms(1) have inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T"
    unfolding is_topology_on_def by blast
  have fin: "finite {Y, V}" by simp
  have sub: "{Y, V} \<subseteq> T" using assms(2) hV by simp
  have "\<Inter>{Y, V} \<in> T" using inter_T fin sub by blast
  moreover have "\<Inter>{Y, V} = Y \<inter> V" by simp
  ultimately show "U \<in> T" using hU by simp
qed

(** from \S16 Theorem 16.3 [top1.tex:492] **)
(** LATEX VERSION: "Product topology on A\<times>B equals subspace topology from X\<times>Y." **)
theorem Theorem_16_3:
  assumes "is_topology_on X TX"
  assumes "is_topology_on Y TY"
  shows "product_topology_on (subspace_topology X TX A) (subspace_topology Y TY B)
       = subspace_topology (X \<times> Y) (product_topology_on TX TY) (A \<times> B)"
  sorry

(** from \S16 Theorem 16.4 [top1.tex:544] **)
(** LATEX VERSION: "If Y is convex in ordered X, then order topology on Y = subspace topology." **)

definition convex_in :: "'a::linorder set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "convex_in X Y \<longleftrightarrow>
     (\<forall>x\<in>Y. \<forall>y\<in>Y. \<forall>z\<in>X. x < z \<and> z < y \<longrightarrow> z \<in> Y)"

theorem Theorem_16_4:
  fixes X :: "'a::linorder set" and Y :: "'a set"
  assumes "convex_in X Y"
  shows "topology_generated_by_basis Y (basis_order_topology \<inter> Pow Y)
       = subspace_topology X order_topology_on_UNIV Y"
  sorry


section \<open>\<S>17 Closed Sets and Limit Points\<close>

subsection \<open>Closed sets\<close>

(** from \S17 Definition (Closed set as complement of open) [top1.tex:~630] **)
definition closedin_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "closedin_on X T A \<longleftrightarrow> A \<subseteq> X \<and> (X - A) \<in> T"

(** de Morgan helper: X - Inter F = Union of (X - A) for A in F **)
lemma diff_Inter_eq: "(X :: 'a set) - \<Inter>F = \<Union>{X - A | A. A \<in> F}"
  apply (rule equalityI)
   apply (rule subsetI)
   apply blast
  apply (rule subsetI)
  apply blast
  done

(** Helper lemmas for closedin_on **)
lemma closedin_sub: "closedin_on X T A \<Longrightarrow> A \<subseteq> X"
  apply (unfold closedin_on_def)
  apply (erule conjE)
  apply assumption
  done

lemma closedin_diff_open: "closedin_on X T A \<Longrightarrow> X - A \<in> T"
  apply (unfold closedin_on_def)
  apply (erule conjE)
  apply assumption
  done

lemma closedin_intro: "A \<subseteq> X \<Longrightarrow> X - A \<in> T \<Longrightarrow> closedin_on X T A"
  apply (unfold closedin_on_def)
  apply (rule conjI)
   apply assumption
  apply assumption
  done

(** from \S17 Theorem 17.1 [top1.tex:640] **)
(** LATEX VERSION: "Empty and X closed; arbitrary intersections closed; finite unions closed." **)
(** Note: Isabelle's Inter {} = UNIV (not X), so the intersection clause needs F \<noteq> {}. **)

(** Auxiliary lemma for Theorem_17_1: finite union of closed sets is closed.
    Use assumes for hfin and hcl, then "using hfin hcl" passes hcl as extra prems
    to finite_induct, giving an IH that includes hcl specialized for the subsets. **)
lemma closedin_Union_finite:
  assumes hT: "is_topology_on X T"
  assumes hfin: "finite F"
  assumes hcl: "\<forall>A\<in>F. closedin_on X T A"
  shows "closedin_on X T (\<Union>F)"
  using hfin hcl
proof (induction rule: finite_induct)
  case empty
  (* ?case = closedin_on X T (\<Union>{}) *)
  (* empty.prems(1) = \<forall>A\<in>{}. closedin_on X T A  [not needed] *)
  have X_T: "X \<in> T"
    by (rule conjunct1[OF conjunct2[OF hT[unfolded is_topology_on_def]]])
  show ?case
    apply (subst Union_empty)
    apply (rule closedin_intro)
     apply (rule empty_subsetI)
    apply (subst Diff_empty)
    apply (rule X_T)
    done
next
  case (insert a G)
  (* ?case = closedin_on X T (\<Union>(insert a G)) *)
  (* insert.hyps(1) = finite G, insert.hyps(2) = a \<notin> G *)
  (* insert.prems(1) = \<forall>A\<in>insert a G. closedin_on X T A  [specialized hcl] *)
  (* insert.IH = (\<forall>A\<in>G. closedin_on X T A) \<Longrightarrow> closedin_on X T (\<Union>G)  [hopefully] *)
  have inter_T: "\<forall>Gf. finite Gf \<and> Gf \<subseteq> T \<longrightarrow> \<Inter>Gf \<in> T"
    by (rule conjunct2[OF conjunct2[OF conjunct2[OF hT[unfolded is_topology_on_def]]]])
  note hall = insert.prems(1)
  have ha: "closedin_on X T a"
    apply (rule bspec[OF hall])
    apply (rule insertI1)
    done
  have hG: "\<forall>A\<in>G. closedin_on X T A"
  proof (rule ballI)
    fix A2 assume hA2G: "A2 \<in> G"
    show "closedin_on X T A2"
      apply (rule bspec[OF hall])
      apply (rule insertI2)
      apply (rule hA2G)
      done
  qed
  have hUG: "closedin_on X T (\<Union>G)"
    by (rule insert.IH[OF hG])
  have a_sub: "a \<subseteq> X" by (rule closedin_sub, rule ha)
  have UG_sub: "\<Union>G \<subseteq> X" by (rule closedin_sub, rule hUG)
  have XmA_T: "X - a \<in> T" by (rule closedin_diff_open, rule ha)
  have XmUG_T: "X - \<Union>G \<in> T" by (rule closedin_diff_open, rule hUG)
  have two_inter: "\<Inter>{X - a, X - \<Union>G} \<in> T"
    apply (rule inter_T[rule_format])
    apply (intro conjI)
     apply (rule finite.insertI, rule finite.insertI, rule finite.emptyI)
    apply (rule subsetI)
    apply (erule insertE)
     apply (erule ssubst, rule XmA_T)
    apply (erule singletonE)
    apply (erule ssubst, rule XmUG_T)
    done
  have inter_eq: "\<Inter>{X - a, X - \<Union>G} = (X - a) \<inter> (X - \<Union>G)"
    by simp
  show ?case
    apply (rule closedin_intro)
     apply (simp only: Union_insert)
     apply (rule Un_least, rule a_sub, rule UG_sub)
    apply (simp only: Union_insert)
    apply (simp only: Diff_Un)
    apply (fold inter_eq)
    apply (rule two_inter)
    done
qed

theorem Theorem_17_1:
  assumes hT: "is_topology_on X T"
  shows "closedin_on X T {} \<and> closedin_on X T X
     \<and> (\<forall>F. F \<noteq> {} \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Inter>F))
     \<and> (\<forall>F. finite F \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Union>F))"
proof -
  (* Extract the four topology axioms *)
  have empty_T: "{} \<in> T"
    by (rule conjunct1[OF hT[unfolded is_topology_on_def]])
  have X_T: "X \<in> T"
    by (rule conjunct1[OF conjunct2[OF hT[unfolded is_topology_on_def]]])
  have union_T: "\<forall>U. U \<subseteq> T \<longrightarrow> \<Union>U \<in> T"
    by (rule conjunct1[OF conjunct2[OF conjunct2[OF hT[unfolded is_topology_on_def]]]])
  have inter_T: "\<forall>G. finite G \<and> G \<subseteq> T \<longrightarrow> \<Inter>G \<in> T"
    by (rule conjunct2[OF conjunct2[OF conjunct2[OF hT[unfolded is_topology_on_def]]]])
  have cl_empty: "closedin_on X T {}"
    apply (rule closedin_intro)
     apply (rule empty_subsetI)
    apply (simp only: Diff_empty)
    apply (rule X_T)
    done
  have cl_X: "closedin_on X T X"
    apply (rule closedin_intro)
     apply (rule subset_refl)
    apply (simp only: Diff_cancel)
    apply (rule empty_T)
    done
  have cl_inter: "\<forall>F. F \<noteq> {} \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Inter>F)"
  proof (intro allI impI)
    fix F :: "'a set set"
    assume hFne: "F \<noteq> {}"
    assume hFcl: "\<forall>A\<in>F. closedin_on X T A"
    obtain A where hAF: "A \<in> F" using hFne by blast
    have cl_A: "closedin_on X T A"
      by (rule bspec[OF hFcl hAF])
    have sub_X: "\<Inter>F \<subseteq> X"
      apply (rule subset_trans)
       apply (rule Inter_lower)
       apply (rule hAF)
      apply (rule closedin_sub)
      apply (rule cl_A)
      done
    have comps_in_T: "{X - A | A. A \<in> F} \<subseteq> T"
    proof (rule subsetI)
      fix B assume hB: "B \<in> {X - A | A. A \<in> F}"
      then obtain A2 where hAF2: "A2 \<in> F" and hBA: "B = X - A2" by blast
      show "B \<in> T"
        apply (subst hBA)
        apply (rule closedin_diff_open)
        apply (rule bspec[OF hFcl hAF2])
        done
    qed
    show "closedin_on X T (\<Inter>F)"
      apply (rule closedin_intro)
       apply (rule sub_X)
      apply (subst diff_Inter_eq)
      apply (rule union_T[rule_format])
      apply (rule comps_in_T)
      done
  qed
  have cl_union: "\<forall>F. finite F \<longrightarrow> (\<forall>A\<in>F. closedin_on X T A) \<longrightarrow> closedin_on X T (\<Union>F)"
    apply (intro allI impI)
    apply (rule closedin_Union_finite[OF hT])
    apply assumption
    apply assumption
    done
  show ?thesis
    apply (intro conjI)
       apply (rule cl_empty)
      apply (rule cl_X)
     apply (rule cl_inter)
    apply (rule cl_union)
    done
qed
(** from \S17 Theorem 17.2 [top1.tex:665] **)
(** LATEX VERSION: "A closed in Y iff A = C\<inter>Y for some closed C in X." **)
(** Note: requires Y \<subseteq> X for the backward direction. **)
theorem Theorem_17_2:
  assumes hT: "is_topology_on X T"
  assumes hYX: "Y \<subseteq> X"
  shows "closedin_on Y (subspace_topology X T Y) A \<longleftrightarrow>
     (\<exists>C. closedin_on X T C \<and> A = C \<inter> Y)"
proof -
  have X_T: "X \<in> T"
    by (rule conjunct1[OF conjunct2[OF hT[unfolded is_topology_on_def]]])
  have inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T"
    by (rule conjunct2[OF conjunct2[OF conjunct2[OF hT[unfolded is_topology_on_def]]]])
  show ?thesis
  proof (rule iffI)
    (* \<rightarrow> direction: closedin_on Y T_Y A \<rightarrow> \<exists>C. closedin_on X T C \<and> A = C \<inter> Y *)
    assume hA: "closedin_on Y (subspace_topology X T Y) A"
    have hAsub: "A \<subseteq> Y" by (rule closedin_sub[OF hA])
    have hYmA: "Y - A \<in> subspace_topology X T Y" by (rule closedin_diff_open[OF hA])
    obtain V where hV: "V \<in> T" and hYmA_eq: "Y - A = Y \<inter> V"
      using hYmA unfolding subspace_topology_def by blast
    (* C = X - V is closed in X *)
    have XV_T: "X \<inter> V \<in> T"
    proof -
      have h1: "finite {X, V}" by simp
      have h2: "{X, V} \<subseteq> T" using X_T hV by simp
      have "\<Inter>{X, V} \<in> T"
        apply (rule inter_T[rule_format])
        apply (rule conjI, rule h1, rule h2)
        done
      thus ?thesis by simp
    qed
    have C_closed: "closedin_on X T (X - V)"
    proof (rule closedin_intro)
      show "X - V \<subseteq> X" by (rule Diff_subset)
      show "X - (X - V) \<in> T"
      proof -
        have eq: "X - (X - V) = X \<inter> V"
          apply (rule equalityI)
           apply (rule subsetI)
           apply blast
          apply (rule subsetI)
          apply blast
          done
        show ?thesis using eq XV_T by simp
      qed
    qed
    (* A = (X - V) \<inter> Y *)
    have A_eq: "A = (X - V) \<inter> Y"
      apply (rule equalityI)
       apply (rule subsetI)
       apply (rule IntI)
        (* x \<in> A \<rightarrow> x \<in> X - V: x \<in> Y (hAsub), x \<in> X (hYX), x \<notin> V (from hYmA_eq) *)
        apply (rule DiffI)
         apply (rule subsetD[OF hYX], rule subsetD[OF hAsub], assumption)
        (* x \<in> A \<rightarrow> x \<notin> V: from Y - A = Y \<inter> V, x \<in> A \<inter> Y \<rightarrow> x \<notin> Y - A \<rightarrow> x \<notin> Y \<inter> V *)
        using hYmA_eq hAsub apply blast
       apply (rule subsetD[OF hAsub], assumption)
      (* (X - V) \<inter> Y \<subseteq> A: x \<in> X - V \<and> x \<in> Y \<rightarrow> x \<notin> V \<rightarrow> x \<notin> Y \<inter> V = Y - A \<rightarrow> x \<in> A *)
      apply (rule subsetI)
      using hYmA_eq apply blast
      done
    show "\<exists>C. closedin_on X T C \<and> A = C \<inter> Y"
      apply (intro exI conjI)
       apply (rule C_closed)
      apply (rule A_eq)
      done
  next
    (* \<leftarrow> direction: \<exists>C. closedin_on X T C \<and> A = C \<inter> Y \<rightarrow> closedin_on Y T_Y A *)
    assume h: "\<exists>C. closedin_on X T C \<and> A = C \<inter> Y"
    then obtain C where hC: "closedin_on X T C" and hA_eq: "A = C \<inter> Y" by blast
    have hXmC_T: "X - C \<in> T" by (rule closedin_diff_open[OF hC])
    have hA_sub: "A \<subseteq> Y"
      apply (subst hA_eq)
      apply (rule Int_lower2)
      done
    (* Y - A = Y \<inter> (X - C) \<in> subspace_topology X T Y *)
    have YmA_eq: "Y - A = Y \<inter> (X - C)"
      apply (subst hA_eq)
      apply (rule equalityI)
       apply (rule subsetI)
       apply (intro IntI)
        apply blast
       apply (intro DiffI)
        apply (rule subsetD[OF hYX], blast)
       apply blast
      apply (rule subsetI)
      apply (intro DiffI)
       apply blast
      apply blast
      done
    have hYmA_in: "Y - A \<in> subspace_topology X T Y"
      apply (subst YmA_eq)
      apply (unfold subspace_topology_def)
      apply (rule CollectI)
      apply (intro exI conjI)
       apply (rule refl)
      apply (rule hXmC_T)
      done
    show "closedin_on Y (subspace_topology X T Y) A"
      apply (rule closedin_intro)
       apply (rule hA_sub)
      apply (rule hYmA_in)
      done
  qed
qed

(** from \S17 Theorem 17.3 [top1.tex:687] **)
(** LATEX VERSION: "If A closed in Y and Y closed in X then A closed in X." **)
theorem Theorem_17_3:
  assumes hT: "is_topology_on X T"
  assumes hY: "closedin_on X T Y"
  assumes hA: "closedin_on Y (subspace_topology X T Y) A"
  shows "closedin_on X T A"
proof -
  from hY have Y_sub_X: "Y \<subseteq> X" and XmY_T: "X - Y \<in> T"
    unfolding closedin_on_def by blast+
  from hA have A_sub_Y: "A \<subseteq> Y"
    unfolding closedin_on_def by blast
  from hA have YmA_sub: "Y - A \<in> subspace_topology X T Y"
    unfolding closedin_on_def by blast
  from YmA_sub obtain V where hV: "V \<in> T" and hYmA: "Y - A = Y \<inter> V"
    unfolding subspace_topology_def by blast
  from hT have XT: "X \<in> T" and
               inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T" and
               union_T: "\<forall>U. U \<subseteq> T \<longrightarrow> \<Union>U \<in> T"
    unfolding is_topology_on_def by blast+
  have XV_T: "X \<inter> V \<in> T"
  proof -
    have "finite {X, V} \<and> {X, V} \<subseteq> T" using XT hV by simp
    then have "\<Inter>{X, V} \<in> T" using inter_T by blast
    then show ?thesis by simp
  qed
  have XmA_eq: "X - A = (X - Y) \<union> (X \<inter> V)"
    using A_sub_Y hYmA by blast
  have XmA_T: "X - A \<in> T"
  proof -
    have "{X - Y, X \<inter> V} \<subseteq> T" using XmY_T XV_T by simp
    then have "\<Union>{X - Y, X \<inter> V} \<in> T" using union_T by blast
    then show ?thesis using XmA_eq by simp
  qed
  show "closedin_on X T A"
    unfolding closedin_on_def using A_sub_Y Y_sub_X XmA_T by blast
qed


subsection \<open>Closure and interior\<close>

(** from \S17 Definition (Interior and closure) [top1.tex:~690] **)
definition interior_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set" where
  "interior_on X T A = \<Union>{U. U \<in> T \<and> U \<subseteq> A}"

definition closure_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> 'a set" where
  "closure_on X T A = \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C}"

(** from \S17 Theorem 17.4 [top1.tex:703] **)
(** LATEX VERSION: "Closure in Y equals closure in X intersect Y." **)
theorem Theorem_17_4:
  assumes hT: "is_topology_on X T"
  assumes hAY: "A \<subseteq> Y" and hYX: "Y \<subseteq> X"
  shows "closure_on Y (subspace_topology X T Y) A = closure_on X T A \<inter> Y"
proof -
  have empty_T: "{} \<in> T"
    by (rule conjunct1[OF hT[unfolded is_topology_on_def]])
  have empty_TY: "{} \<in> subspace_topology X T Y"
    apply (unfold subspace_topology_def)
    apply (rule CollectI)
    apply (rule exI[where x="{}"])
    apply (rule conjI)
     apply (simp only: Int_empty_right)
    apply (rule empty_T)
    done
  have Y_closed: "closedin_on Y (subspace_topology X T Y) Y"
    apply (rule closedin_intro)
     apply (rule subset_refl)
    apply (simp only: Diff_cancel)
    apply (rule empty_TY)
    done
  note t172 = Theorem_17_2[OF hT hYX]
  show ?thesis
  proof (rule equalityI)
    show "closure_on Y (subspace_topology X T Y) A \<subseteq> closure_on X T A \<inter> Y"
      unfolding closure_on_def
    proof (rule subsetI)
      fix x
      assume hx: "x \<in> \<Inter>{C. closedin_on Y (subspace_topology X T Y) C \<and> A \<subseteq> C}"
      show "x \<in> \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C} \<inter> Y"
      proof (rule IntI)
        show "x \<in> \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C}"
        proof (rule InterI)
          fix D assume hD: "D \<in> {C. closedin_on X T C \<and> A \<subseteq> C}"
          have hDcl: "closedin_on X T D"
            by (rule conjunct1[OF CollectD[OF hD]])
          have hAD: "A \<subseteq> D"
            by (rule conjunct2[OF CollectD[OF hD]])
          have DY_cl: "closedin_on Y (subspace_topology X T Y) (D \<inter> Y)"
            apply (rule iffD2[OF t172])
            apply (intro exI conjI, rule hDcl, rule refl)
            done
          have A_DY: "A \<subseteq> D \<inter> Y"
            apply (rule subsetI, rule IntI)
             apply (rule subsetD[OF hAD], assumption)
            apply (rule subsetD[OF hAY], assumption)
            done
          have x_DY: "x \<in> D \<inter> Y"
            apply (rule InterD[OF hx])
            apply (rule CollectI, rule conjI, rule DY_cl, rule A_DY)
            done
          show "x \<in> D"
            by (rule IntD1[OF x_DY])
        qed
        show "x \<in> Y"
          apply (rule InterD[OF hx])
          apply (rule CollectI, rule conjI, rule Y_closed, rule hAY)
          done
      qed
    qed
  next
    show "closure_on X T A \<inter> Y \<subseteq> closure_on Y (subspace_topology X T Y) A"
      unfolding closure_on_def
    proof (rule subsetI)
      fix x
      assume hx: "x \<in> \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C} \<inter> Y"
      have hxcl: "x \<in> \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C}"
        by (rule IntD1[OF hx])
      have hxY: "x \<in> Y"
        by (rule IntD2[OF hx])
      show "x \<in> \<Inter>{C. closedin_on Y (subspace_topology X T Y) C \<and> A \<subseteq> C}"
      proof (rule InterI)
        fix C assume hC: "C \<in> {B. closedin_on Y (subspace_topology X T Y) B \<and> A \<subseteq> B}"
        have hCcl: "closedin_on Y (subspace_topology X T Y) C"
          by (rule conjunct1[OF CollectD[OF hC]])
        have hAC: "A \<subseteq> C"
          by (rule conjunct2[OF CollectD[OF hC]])
        have hCD_ex: "\<exists>D. closedin_on X T D \<and> C = D \<inter> Y"
          by (rule iffD1[OF t172, OF hCcl])
        then obtain D where hDcl: "closedin_on X T D" and hCD: "C = D \<inter> Y"
          by blast
        have hAD: "A \<subseteq> D"
          apply (rule subset_trans[OF hAC])
          apply (subst hCD, rule Int_lower1)
          done
        have xD: "x \<in> D"
          apply (rule InterD[OF hxcl])
          apply (rule CollectI, rule conjI, rule hDcl, rule hAD)
          done
        show "x \<in> C"
          apply (subst hCD, rule IntI, rule xD, rule hxY)
          done
      qed
    qed
  qed
qed

(** from \S17 (Terminology: 'A intersects B' iff A\<inter>B \<noteq> {}) [top1.tex:~707] **)
definition intersects :: "'a set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "intersects A B \<longleftrightarrow> A \<inter> B \<noteq> {}"

(** from \S17 Theorem 17.5 [top1.tex:713] **)
(** LATEX VERSION: "x\<in>Cl A iff every open neighborhood intersects A; basis version too." **)
definition neighborhood_of :: "'a \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set \<Rightarrow> bool" where
  "neighborhood_of x X T U \<longleftrightarrow> U \<in> T \<and> x \<in> U"

theorem Theorem_17_5a:
  assumes hT: "is_topology_on X T"
  assumes hxX: "x \<in> X" and hAX: "A \<subseteq> X"
  shows "x \<in> closure_on X T A \<longleftrightarrow>
    (\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A)"
proof (rule iffI)
  assume hx: "x \<in> closure_on X T A"
  show "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A"
  proof (intro allI impI)
    fix U assume hU: "neighborhood_of x X T U"
    have hUT: "U \<in> T"
      by (rule conjunct1[OF hU[unfolded neighborhood_of_def]])
    have hxU: "x \<in> U"
      by (rule conjunct2[OF hU[unfolded neighborhood_of_def]])
    have X_T: "X \<in> T"
      by (rule conjunct1[OF conjunct2[OF hT[unfolded is_topology_on_def]]])
    have inter_T: "\<forall>F. finite F \<and> F \<subseteq> T \<longrightarrow> \<Inter>F \<in> T"
      by (rule conjunct2[OF conjunct2[OF conjunct2[OF hT[unfolded is_topology_on_def]]]])
    have XU_T: "X \<inter> U \<in> T"
    proof -
      have "finite {X, U} \<and> {X, U} \<subseteq> T" using X_T hUT by simp
      then have "\<Inter>{X, U} \<in> T" using inter_T by blast
      then show ?thesis by simp
    qed
    have XmU_closed: "closedin_on X T (X - U)"
      apply (rule closedin_intro, rule Diff_subset)
      apply (simp only: Diff_Diff_Int)
      apply (rule XU_T)
      done
    show "intersects U A"
      unfolding intersects_def
    proof (rule notI)
      assume h: "U \<inter> A = {}"
      have A_sub_XmU: "A \<subseteq> X - U"
        using h hAX by blast
      have x_in_XmU: "x \<in> X - U"
        apply (rule InterD[OF hx[unfolded closure_on_def]])
        apply (rule CollectI, rule conjI, rule XmU_closed, rule A_sub_XmU)
        done
      show False
        by (rule DiffD2[OF x_in_XmU, OF hxU])
    qed
  qed
next
  assume h: "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A"
  show "x \<in> closure_on X T A"
    unfolding closure_on_def
  proof (rule InterI)
    fix C assume hC: "C \<in> {D. closedin_on X T D \<and> A \<subseteq> D}"
    have hCcl: "closedin_on X T C"
      by (rule conjunct1[OF CollectD[OF hC]])
    have hAC: "A \<subseteq> C"
      by (rule conjunct2[OF CollectD[OF hC]])
    have hXmCT: "X - C \<in> T"
      by (rule closedin_diff_open[OF hCcl])
    show "x \<in> C"
    proof (rule ccontr)
      assume hxnC: "x \<notin> C"
      have hxXmC: "x \<in> X - C"
        apply (rule DiffI, rule hxX, rule hxnC) done
      have hneigh: "neighborhood_of x X T (X - C)"
        apply (unfold neighborhood_of_def, rule conjI, rule hXmCT, rule hxXmC) done
      have hinters: "intersects (X - C) A"
        by (rule h[rule_format, OF hneigh])
      have hdisjoint: "(X - C) \<inter> A = {}"
        using hAC by blast
      show False
        apply (rule notE[OF hinters[unfolded intersects_def]])
        apply (rule hdisjoint)
        done
    qed
  qed
qed

theorem Theorem_17_5b:
  assumes hB: "basis_for X B T"
  assumes hxX: "x \<in> X" and hAX: "A \<subseteq> X"
  shows "x \<in> closure_on X T A \<longleftrightarrow>
    (\<forall>b\<in>B. x \<in> b \<longrightarrow> intersects b A)"
proof (rule iffI)
  (* Forward direction needs basis elements \<subseteq> X, which is_basis_on doesn't force *)
  assume "x \<in> closure_on X T A"
  show "\<forall>b\<in>B. x \<in> b \<longrightarrow> intersects b A" sorry
next
  assume h: "\<forall>b\<in>B. x \<in> b \<longrightarrow> intersects b A"
  show "x \<in> closure_on X T A"
    unfolding closure_on_def
  proof (rule InterI)
    fix C assume hC: "C \<in> {D. closedin_on X T D \<and> A \<subseteq> D}"
    have hCcl: "closedin_on X T C"
      by (rule conjunct1[OF CollectD[OF hC]])
    have hAC: "A \<subseteq> C"
      by (rule conjunct2[OF CollectD[OF hC]])
    have hXmCT: "X - C \<in> T"
      by (rule closedin_diff_open[OF hCcl])
    have hT_def: "T = topology_generated_by_basis X B"
      by (rule conjunct2[OF hB[unfolded basis_for_def]])
    show "x \<in> C"
    proof (rule ccontr)
      assume hxnC: "x \<notin> C"
      have hxXmC: "x \<in> X - C"
        apply (rule DiffI, rule hxX, rule hxnC) done
      have hXmC_basis: "X - C \<in> topology_generated_by_basis X B"
        using hXmCT hT_def by simp
      have hex_b: "\<exists>b\<in>B. x \<in> b \<and> b \<subseteq> X - C"
        using hXmC_basis hxXmC
        unfolding topology_generated_by_basis_def
        by blast
      then obtain b where hbB: "b \<in> B" and hxb: "x \<in> b" and hbsub: "b \<subseteq> X - C"
        by blast
      have hinters: "intersects b A"
        by (rule h[rule_format, OF hbB, OF hxb])
      have hdisjoint: "b \<inter> A = {}"
        using hbsub hAC by blast
      show False
        apply (rule notE[OF hinters[unfolded intersects_def]])
        apply (rule hdisjoint)
        done
    qed
  qed
qed


subsection \<open>Limit points\<close>

(** from \S17 Definition (Limit point) [top1.tex:~742] **)
definition is_limit_point_of :: "'a \<Rightarrow> 'a set \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_limit_point_of x A X T \<longleftrightarrow>
     x \<in> X \<and> A \<subseteq> X \<and>
     (\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects (U - {x}) A)"

definition limit_points_of :: "'a set \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> 'a set" where
  "limit_points_of A X T = {x\<in>X. is_limit_point_of x A X T}"

(** from \S17 Theorem 17.6 [top1.tex:751] **)
(** LATEX VERSION: "Cl A = A \<union> A'." **)
theorem Theorem_17_6:
  assumes hT: "is_topology_on X T"
  assumes hAX: "A \<subseteq> X"
  shows "closure_on X T A = A \<union> limit_points_of A X T"
proof (rule equalityI)
  show "closure_on X T A \<subseteq> A \<union> limit_points_of A X T"
  proof (rule subsetI)
    fix x assume hx: "x \<in> closure_on X T A"
    have empty_T: "{} \<in> T"
      by (rule conjunct1[OF hT[unfolded is_topology_on_def]])
    have cl_X: "closedin_on X T X"
      apply (rule closedin_intro, rule subset_refl)
      apply (simp only: Diff_cancel)
      apply (rule empty_T)
      done
    have x_in_X: "x \<in> X"
      apply (rule InterD[OF hx[unfolded closure_on_def]])
      apply (rule CollectI, rule conjI, rule cl_X, rule hAX)
      done
    show "x \<in> A \<union> limit_points_of A X T"
    proof (cases "x \<in> A")
      case True show ?thesis by (rule UnI1, rule True)
    next
      case False
      have hxnA: "x \<notin> A" by (rule False)
      have h5a: "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A"
        by (rule iffD1[OF Theorem_17_5a[OF hT x_in_X hAX], OF hx])
      have x_lp: "is_limit_point_of x A X T"
        unfolding is_limit_point_of_def
      proof (intro conjI)
        show "x \<in> X" by (rule x_in_X)
        show "A \<subseteq> X" by (rule hAX)
        show "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects (U - {x}) A"
        proof (intro allI impI)
          fix U assume hU: "neighborhood_of x X T U"
          have hUA_ne: "U \<inter> A \<noteq> {}"
            using h5a[rule_format, OF hU] unfolding intersects_def .
          show "intersects (U - {x}) A"
            unfolding intersects_def
          proof (rule notI)
            assume h: "(U - {x}) \<inter> A = {}"
            have UA_empty: "U \<inter> A = {}"
              using h hxnA by blast
            from UA_empty hUA_ne show False by simp
          qed
        qed
      qed
      show "x \<in> A \<union> limit_points_of A X T"
        apply (rule UnI2)
        apply (unfold limit_points_of_def)
        apply (rule CollectI, rule conjI, rule x_in_X, rule x_lp)
        done
    qed
  qed
next
  show "A \<union> limit_points_of A X T \<subseteq> closure_on X T A"
  proof (rule subsetI)
    fix x assume hx: "x \<in> A \<union> limit_points_of A X T"
    show "x \<in> closure_on X T A"
    proof (cases "x \<in> A")
      case True
      have x_in_X: "x \<in> X" by (rule subsetD[OF hAX True])
      show ?thesis
        unfolding closure_on_def
      proof (rule InterI)
        fix C assume hC: "C \<in> {D. closedin_on X T D \<and> A \<subseteq> D}"
        have hAC: "A \<subseteq> C" by (rule conjunct2[OF CollectD[OF hC]])
        show "x \<in> C" by (rule subsetD[OF hAC True])
      qed
    next
      case False
      have hxnA: "x \<notin> A" by (rule False)
      have hxlp: "x \<in> limit_points_of A X T"
        using hx hxnA by blast
      have hx_def: "is_limit_point_of x A X T"
        using hxlp unfolding limit_points_of_def by blast
      have x_in_X: "x \<in> X"
        using hx_def unfolding is_limit_point_of_def by blast
      have hlp_nbds: "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects (U - {x}) A"
        using hx_def unfolding is_limit_point_of_def by blast
      have h_all_nbds: "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects U A"
      proof (intro allI impI)
        fix U assume hU: "neighborhood_of x X T U"
        have h_sub_int: "intersects (U - {x}) A"
          by (rule hlp_nbds[rule_format, OF hU])
        show "intersects U A"
          unfolding intersects_def
        proof (rule notI)
          assume h: "U \<inter> A = {}"
          have h2: "(U - {x}) \<inter> A = {}"
            using h by blast
          from h_sub_int[unfolded intersects_def] h2 show False by simp
        qed
      qed
      show ?thesis
        by (rule iffD2[OF Theorem_17_5a[OF hT x_in_X hAX], OF h_all_nbds])
    qed
  qed
qed

(** from \S17 Corollary 17.7 [top1.tex:761] **)
(** LATEX VERSION: "A closed iff contains all its limit points." **)
theorem Corollary_17_7:
  assumes hT: "is_topology_on X T"
  assumes hAX: "A \<subseteq> X"
  shows "closedin_on X T A \<longleftrightarrow> limit_points_of A X T \<subseteq> A"
proof (rule iffI)
  assume hAcl: "closedin_on X T A"
  show "limit_points_of A X T \<subseteq> A"
  proof (rule subsetI)
    fix x assume hxlp: "x \<in> limit_points_of A X T"
    have hx_def: "is_limit_point_of x A X T"
      using hxlp unfolding limit_points_of_def by blast
    have hxX: "x \<in> X"
      using hx_def unfolding is_limit_point_of_def by blast
    have hlp_nbds: "\<forall>U. neighborhood_of x X T U \<longrightarrow> intersects (U - {x}) A"
      using hx_def unfolding is_limit_point_of_def by blast
    show "x \<in> A"
    proof (rule ccontr)
      assume hxnA: "x \<notin> A"
      have hXmAT: "X - A \<in> T" by (rule closedin_diff_open[OF hAcl])
      have hxXmA: "x \<in> X - A" by (rule DiffI, rule hxX, rule hxnA)
      have hneigh: "neighborhood_of x X T (X - A)"
        apply (unfold neighborhood_of_def, rule conjI, rule hXmAT, rule hxXmA) done
      have hinters: "intersects (X - A - {x}) A"
        by (rule hlp_nbds[rule_format, OF hneigh])
      have hdisjoint: "(X - A - {x}) \<inter> A = {}"
        by blast
      show False
        apply (rule notE[OF hinters[unfolded intersects_def]])
        apply (rule hdisjoint)
        done
    qed
  qed
next
  assume hlp: "limit_points_of A X T \<subseteq> A"
  have empty_T: "{} \<in> T"
    by (rule conjunct1[OF hT[unfolded is_topology_on_def]])
  have X_closed: "closedin_on X T X"
    apply (rule closedin_intro, rule subset_refl)
    apply (simp only: Diff_cancel, rule empty_T) done
  have cl_inter: "\<forall>F. F \<noteq> {} \<longrightarrow> (\<forall>C\<in>F. closedin_on X T C) \<longrightarrow> closedin_on X T (\<Inter>F)"
    by (rule conjunct1[OF conjunct2[OF conjunct2[OF Theorem_17_1[OF hT]]]])
  have F_ne: "{C. closedin_on X T C \<and> A \<subseteq> C} \<noteq> {}"
  proof (rule notI)
    assume h: "{C. closedin_on X T C \<and> A \<subseteq> C} = {}"
    have "X \<in> {C. closedin_on X T C \<and> A \<subseteq> C}"
      apply (rule CollectI, rule conjI, rule X_closed, rule hAX) done
    from h this show False by blast
  qed
  have cl_closed: "closedin_on X T (closure_on X T A)"
    unfolding closure_on_def
  proof (rule cl_inter[rule_format, OF F_ne])
    fix C assume hC: "C \<in> {D. closedin_on X T D \<and> A \<subseteq> D}"
    show "closedin_on X T C" by (rule conjunct1[OF CollectD[OF hC]])
  qed
  have cl_eq: "closure_on X T A = A"
  proof (rule equalityI)
    show "closure_on X T A \<subseteq> A"
      apply (subst Theorem_17_6[OF hT hAX])
      apply (rule Un_least, rule subset_refl, rule hlp)
      done
    show "A \<subseteq> closure_on X T A"
      unfolding closure_on_def
    proof (rule subsetI)
      fix a assume ha: "a \<in> A"
      show "a \<in> \<Inter>{C. closedin_on X T C \<and> A \<subseteq> C}"
      proof (rule InterI)
        fix C assume hC: "C \<in> {D. closedin_on X T D \<and> A \<subseteq> D}"
        show "a \<in> C" by (rule subsetD[OF conjunct2[OF CollectD[OF hC]], OF ha])
      qed
    qed
  qed
  show "closedin_on X T A"
    using cl_closed by (simp only: cl_eq)
qed


subsection \<open>Hausdorff spaces, T1 axiom, sequences\<close>

(** from \S17 Definition (Hausdorff space) [top1.tex:780] **)
(** LATEX VERSION: "Distinct points have disjoint neighborhoods." **)
definition is_hausdorff_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "is_hausdorff_on X T \<longleftrightarrow>
     is_topology_on X T \<and>
     (\<forall>x\<in>X. \<forall>y\<in>X. x \<noteq> y \<longrightarrow>
        (\<exists>U V. neighborhood_of x X T U \<and> neighborhood_of y X T V \<and> U \<inter> V = {}))"

(** from \S17 Theorem 17.8 [top1.tex:782] **)
(** LATEX VERSION: "Every finite point set in Hausdorff space is closed." **)
theorem Theorem_17_8:
  assumes "is_hausdorff_on X T"
  assumes "finite A" and "A \<subseteq> X"
  shows "closedin_on X T A"
  sorry

(** from \S17 (T1 axiom) [top1.tex:~785] **)
definition satisfies_T1_on :: "'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "satisfies_T1_on X T \<longleftrightarrow> is_topology_on X T \<and> (\<forall>x\<in>X. closedin_on X T {x})"

(** from \S17 Theorem 17.9 [top1.tex:787] **)
(** LATEX VERSION: "In a T1 space, x is limit point of A iff every neighborhood contains infinitely many points of A." **)
theorem Theorem_17_9:
  assumes "satisfies_T1_on X T"
  assumes "A \<subseteq> X" and "x \<in> X"
  shows "is_limit_point_of x A X T \<longleftrightarrow>
    (\<forall>U. neighborhood_of x X T U \<longrightarrow> infinite (U \<inter> A))"
  sorry

(** from \S17 (Definition of sequence convergence) [top1.tex:~770] **)
definition seq_converges_to_on :: "(nat \<Rightarrow> 'a) \<Rightarrow> 'a \<Rightarrow> 'a set \<Rightarrow> 'a set set \<Rightarrow> bool" where
  "seq_converges_to_on s x X T \<longleftrightarrow>
     x \<in> X \<and>
     (\<forall>U. neighborhood_of x X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U))"

(** from \S17 Theorem 17.10 [top1.tex:801] **)
(** LATEX VERSION: "In Hausdorff space, a sequence converges to at most one point." **)
theorem Theorem_17_10:
  assumes "is_hausdorff_on X T"
  assumes "seq_converges_to_on s x X T"
  assumes "seq_converges_to_on s y X T"
  shows "x = y"
proof (rule ccontr)
  assume neq: "x \<noteq> y"
  from assms(1) have hausdorff: "\<forall>a\<in>X. \<forall>b\<in>X. a \<noteq> b \<longrightarrow>
      (\<exists>U V. neighborhood_of a X T U \<and> neighborhood_of b X T V \<and> U \<inter> V = {})"
    unfolding is_hausdorff_on_def by blast
  from assms(2) have hx: "x \<in> X"
    and conv_x: "\<forall>U. neighborhood_of x X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U)"
    unfolding seq_converges_to_on_def by blast+
  from assms(3) have hy: "y \<in> X"
    and conv_y: "\<forall>U. neighborhood_of y X T U \<longrightarrow> (\<exists>N. \<forall>n\<ge>N. s n \<in> U)"
    unfolding seq_converges_to_on_def by blast+
  from hausdorff hx hy neq obtain U V where
    hU: "neighborhood_of x X T U" and hV: "neighborhood_of y X T V" and disj: "U \<inter> V = {}"
    by blast
  from conv_x hU obtain N1 where N1: "\<forall>n\<ge>N1. s n \<in> U" by blast
  from conv_y hV obtain N2 where N2: "\<forall>n\<ge>N2. s n \<in> V" by blast
  have "s (max N1 N2) \<in> U \<inter> V"
    using N1[rule_format, of "max N1 N2"] N2[rule_format, of "max N1 N2"] by auto
  with disj show False by simp
qed

(** from \S17 Theorem 17.11 [top1.tex:809] **)
(** LATEX VERSION: "Order topology on simply ordered set is Hausdorff; products/subspaces preserve Hausdorff." **)
theorem Theorem_17_11:
  shows
    "(\<forall>(X::'a::linorder set). is_hausdorff_on X order_topology_on_UNIV)
     \<and> (\<forall>X1 T1 X2 T2.
            is_hausdorff_on X1 T1 \<and> is_hausdorff_on X2 T2 \<longrightarrow>
            is_hausdorff_on (X1 \<times> X2) (product_topology_on T1 T2))
     \<and> (\<forall>X T Y.
            is_hausdorff_on X T \<and> Y \<subseteq> X \<longrightarrow>
            is_hausdorff_on Y (subspace_topology X T Y))"
  sorry

end
